// <auto-generated />
namespace KAT.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddCodes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCodes));
        
        string IMigrationMetadata.Id
        {
            get { return "201605152357027_AddCodes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
